### ISSUE TITLE
checksum function need sha256 twice?

### ISSUE THREAD

**Issue by PandaTea** [in3rsha/learnmeabitcoin-code#2]
learnmeabitcoin-code/checksum.rb
```
def checksum(hex)
  hash = hash256(hex) # Hash the data through SHA256 twice
  return hash[0...8]  # Return the first 4 bytes (8 characters)
end
```
hash = hash256(hash256(hex))

this is a great repository,love you ( 0 3 0 )

**Comment by in3rsha** [comment]
Yes that's right. In the code I was referring to the `hash256` function from the `hash256.rb` file, which basically does `sha256(sha256(hex))` already.

I can see why that wasn't clear though, so I've included the `hash256` function to the top of the `checksum.rb` file.

Thanks for that, and thanks for the kind words :)
