### ISSUE TITLE
Invalid TXID at the website

### ISSUE THREAD

**Issue by sharifzadesina** [in3rsha/learnmeabitcoin-code#3]
Hello Greg, thank you for creating such a great website.
The TXID in the link below is invalid and refers to a false transaction.
https://learnmeabitcoin.com/guide/input
It should be changed from "0d0897966df95d0b8e7a33855a64f7de365e7d17e28f2a05c39806e77d5f9859" to "c1b4e695098210a31fe02abffe9005cffc051bbe86ff33e173155bcbdc5821e3", like other pages.
P.S. I didn't know here is a good place to report this issue or no, but anyway I didn't find anywhere better.
![screenshot-learnmeabitcoin com-2020 02 15-00_07_29](https://user-images.githubusercontent.com/15300551/74565901-7d531e80-4f87-11ea-8c65-6d905e2bbf78.png)
![screenshot-learnmeabitcoin com-2020 02 15-00_08_23](https://user-images.githubusercontent.com/15300551/74565907-80e6a580-4f87-11ea-8985-f33f9813e535.png)

**Comment by in3rsha** [comment]
Nice spot, thank you. Just updated the TXIDs on the page.

Did you hash256 the raw transaction data to spot that mistake?

Greg.

P.S. Here is cool for issues.

**Comment by sharifzadesina** [comment]
your welcome bro.
no, I used blockchair.com, it has a feature to show raw transaction data.

**Comment by sharifzadesina** [comment]
@in3rsha 
I just encountered the same problem exists also in this page:
https://learnmeabitcoin.com/guide/output

**Comment by in3rsha** [comment]
Fixed that too. Should have done a site-wide search.

Thanks again.
