### ISSUE TITLE
Invalid timestamp highlight

### ISSUE THREAD

**Issue by wbarobinson** [in3rsha/learnmeabitcoin-code#4]
Hello! I very much enjoyed your website. While doing some double checking to make sure I understood things, I stumbled upon a UI issue with your blockheader example. The timestamp isnt highlighting the leftmost character. As a result it looks 7 characters long instead of 8. Cheers! Great stuff.

**Comment by in3rsha** [comment]
Hi William,

That is a great spot, thank you. Just updated the page!

Greg.

**Comment by wbarobinson** [comment]
My absolute pleasure!

Will

**Comment by wbarobinson** [comment]
Just noticed something else...

On the blockheader page you mention that the previous hash is in
Big-Endian, but I think it is Little-Endian. The reason this must be true
is because the blockhash must be smaller than the target, which means the
trailing zeroes must become the most significant digits.
