### ISSUE TITLE
Transaction data structure description outdated

### ISSUE THREAD

**Issue by staktrace** [in3rsha/learnmeabitcoin-code#8]
Hi! Thank you for creating the learnmeabitcoin website, it's been super helpful to me! I started implementing some pieces of Bitcoin to get a better handle on it, and noticed that the transaction data structure described at https://learnmeabitcoin.com/technical/transaction-data is not current, since the Bitcoin core code has this [flags field](https://github.com/bitcoin/bitcoin/blob/e191fac4f3c37820f0618f72f0a8e8b524531ab8/src/primitives/transaction.h#L208) that can appear sometimes.

I wasn't really sure where to report this or if I can just make a PR to update it, so I'm filing this issue hoping you see it. Thanks!

**Comment by in3rsha** [comment]
Hi Kartikaya,

I'm currently doing a rewrite of the website and this is a section that I'm updating. It should be ready at the start of the new year (it's taking a bit of a while).

Thank you for the reminder. I appreciate it.

Greg.

P.S. Opening an issue here is cool, or if you prefer you can email me: {myfirstname} [at] {thenameofthewebsite} [dot] com

**Comment by staktrace** [comment]
Sounds good, thank you!
